export * from './LandingPage'
export * from './LoginPage'
export * from './RegisterPage'
export * from './SetupHotelPage'
export * from './DashboardPage'
export * from './LiveDemoPage'
export { default as ShiftStartPage } from './ShiftStartPage'
export * from './PricingPage'
export * from './HowItWorksPage'
export * from './BlogPage'
export * from './UpdatesPage'
export * from './FeaturesPage'
export * from './BlogPostPage'
export * from './ContactPage'
